services:
  - type: web
    name: ias-backend
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-143.0.7499.169/chrome-linux64/chrome
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
