services:
  - type: web
    name: ias-backend
    runtime: node
    buildCommand: npm install && npx @puppeteer/browsers install chrome@stable --path /opt/render/project/.chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/.chrome/chrome/linux-131.0.6778.108/chrome-linux64/chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'
