services:
  - type: web
    name: ias-backend
    runtime: node
    buildCommand: |
      npm install
      apt-get update
      apt-get install -y chromium-browser
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'true'
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: NODE_ENV
        value: production
